### PR TITLE
Update project tt_um_rebeccargb_vga_pride (RebeccaRGB/tt-vga-pride)

### PR DESCRIPTION
**Pull request by TinyTapeoutBot**
Update project tt_um_rebeccargb_vga_pride to commit RebeccaRGB/tt-vga-pride@b9dae12f79321c990884aac542c9197e5653cde8

Project title: VGA Pride
Tiles: 1x2
Workflow: https://github.com/RebeccaRGB/tt-vga-pride/actions/runs/11711476113

### CODE REVIEW

**Comment by urish** [comment]
@RebeccaRGB note that we've decided to revert the config.json change in the template, and we'll apply a fix during the chip integration (see commit 8c72b8a6c36228640f6751a210c1461d9059abdc). 

There's no need to resubmit the projects that you have updated today (it'll work well with or without the change), but there's also no need to keep updating past projects.

**Comment by RebeccaRGB** [comment]
Doesn't that only fix the issue for Wokwi projects though? Or is it only/mostly Wokwi projects that are running into it due to low utilization?

**Comment by urish** [comment]
Mostly projects with low utilization, which are all Wokwi projects. We now have automatic reporting of the poly utilization of the final gds, so if it grows too high we'll enable the fix for additional projects. 

The reason we don't want to go overboard with this, is that the decap3 cells have higher local interconnect (LI) utilization, so if everyone switches to that, it can also be an issue.

**Comment by RebeccaRGB** [comment]
I see. That makes sense. Thanks.

**Pull request merged**
